// AUTOGENERATED BY MOSKV-1 APEX CO-DESIGN
// Bare-metal C FFI acceleration target
#include <stdio.h>

float calculate_exergy_ratio(int mutations, int token_cost) {
    if (token_cost == 0) return 0.0f;
    return (float)mutations / (token_cost * 0.01f);
}
